### ISSUE TITLE
 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by emnab** [Jeff-Zilence/Explain_Metric_Learning#1]
Hi, i m trying to use Face_Verification demo in colab with GPU, I got this error :  
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper__native_batch_norm_backward)

It seems as if the the model is on the GPU but the data is on the CPU. I have tried several things but nothing worked and I believe I just can't find the correct line of code to change.
Could you please help me? Thank you.

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. I did not encounter this issue when I tested it on my machine. Could you provide more detailed log for this issue? It is hard to figure out given limited information. This might be some environment or pytorch version issue (it was using a very old pytorch version). If all the environment and versions are the same, then you might remove all the cuda() and use cpu mode. It is just a test on two images and should be fast even on cpu.

**Comment by emnab** [comment]
Thank you for your response 
I removed all the cuda() and used cpu mode it's working now 
Thank you for your help
